language: node_js
node_js:
  - "6"
  - "8"
  - "10"
script: npm test
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_AUTH_KEY
  on:
    branch: dev-0.0.1
    tags: true
    repo: onlychild/Cypress-junit-reporter
